ESTADO_MOTORES = ('a', 'b', 'c', 'd', 'ea', 'ef', 'dc')

RANGE_NUMERIC_KEY = (48, 57)
SCREEN_X = (888)
SCREEN_Y = (666)
SCREEN_SIZE = (SCREEN_X, SCREEN_Y)

BLACK = (0, 0, 0)
WHITE = (254, 254, 254)
GRAY = (200, 200, 200)

BUTTON_WIDTH = (163)
BUTTON_HEIGHT = (55)
BUTTON_SIZE = (BUTTON_WIDTH, BUTTON_HEIGHT)

ROBO_X = (-30)
ROBO_Y = (15)
ROBO_POS = (ROBO_X, ROBO_Y)
ROBO_WIDTH = (631)
ROBO_HEIGHT = (586)
ROBO_SIZE = (ROBO_WIDTH, ROBO_HEIGHT)

MOTOR1_X = (35)
MOTOR1_Y = (595)

MOTOR2_X = (35)
MOTOR2_Y = (290)

MOTOR3_X = (35)
MOTOR3_Y = (10)

MOTOR4_X = (300)
MOTOR4_Y = (10)

ABRIR_X = (537)
ABRIR_Y = (85)
FECHAR_X = (707)
FECHAR_Y = (85)

MOTOR1_POS = (MOTOR1_X, MOTOR1_Y)
MOTOR2_POS = (MOTOR2_X, MOTOR2_Y)
MOTOR3_POS = (MOTOR3_X, MOTOR3_Y)
MOTOR4_POS = (MOTOR4_X, MOTOR4_Y)
ABRIR_POS = (ABRIR_X, ABRIR_Y)
FECHAR_POS = (FECHAR_X, FECHAR_Y)

DISC_CONN_X = (537)
DISC_CONN_Y = (10)
DISC_CONN_POS = (DISC_CONN_X, DISC_CONN_Y)
DISC_CONN_WIDTH = (333)
DISC_CONN_HEIGHT = (55)
DISC_CONN_SIZE = (DISC_CONN_WIDTH, DISC_CONN_HEIGHT)

CAMERA_X = (230)
CAMERA_Y = (170)
CAMERA_POS = (CAMERA_X, CAMERA_Y)
CAMERA_WIDTH = (640)
CAMERA_HEIGHT = (480)
CAMERA_SIZE = (CAMERA_WIDTH, CAMERA_HEIGHT)
