ESTADO_MOTORES = ('a', 'b', 'c', 'd', 'ea', 'ef')

RANGE_NUMERIC_KEY = (48, 57)
SCREEN_X = (888)
SCREEN_Y = (666)
SCREEN_SIZE = (SCREEN_X, SCREEN_Y)

BLACK = (0, 0, 0)
WHITE = (254, 254, 254)
GRAY = (200, 200, 200)

BUTTON_WIDTH = (70)
BUTTON_HEIGHT = (70)
BUTTON_SIZE = (BUTTON_WIDTH, BUTTON_HEIGHT)

ROBO_X = (-30)
ROBO_Y = (15)
ROBO_POS = (ROBO_X, ROBO_Y)
ROBO_WIDTH = (631)
ROBO_HEIGHT = (586)
ROBO_SIZE = (ROBO_WIDTH, ROBO_HEIGHT)

BUTTON0_X = (45)
BUTTON0_Y = (10)

BUTTON1_X = (140)
BUTTON1_Y = (10)

BUTTON2_X = (45)
BUTTON2_Y = (110)

BUTTON3_X = (140)
BUTTON3_Y = (110)

ABRIR_X = (45)
ABRIR_Y = (210)
FECHAR_X = (140)
FECHAR_Y = (210)

BUTTON0_POS = (BUTTON0_X, BUTTON0_Y)
BUTTON1_POS = (BUTTON1_X, BUTTON1_Y)
BUTTON2_POS = (BUTTON2_X, BUTTON2_Y)
BUTTON3_POS = (BUTTON3_X, BUTTON3_Y)
ABRIR_POS = (ABRIR_X, ABRIR_Y)
FECHAR_POS = (FECHAR_X, FECHAR_Y)

DISC_CONN_X = (537)
DISC_CONN_Y = (10)
DISC_CONN_POS = (DISC_CONN_X, DISC_CONN_Y)
DISC_CONN_WIDTH = (333)
DISC_CONN_HEIGHT = (55)
DISC_CONN_SIZE = (DISC_CONN_WIDTH, DISC_CONN_HEIGHT)

CAMERA_X = (230)
CAMERA_Y = (170)
CAMERA_POS = (CAMERA_X, CAMERA_Y)
CAMERA_WIDTH = (640)
CAMERA_HEIGHT = (480)
CAMERA_SIZE = (CAMERA_WIDTH, CAMERA_HEIGHT)
